use_frameworks!

target 'KIF-Quick_Example' do

  target 'KIF-Quick_Tests' do
    inherit! :search_paths

    pod 'KIF-Quick', :path => '../'
    pod 'Nimble', '4.1.0'   # Swift 2.3 compatible
  end
end
