use_frameworks!

target 'KIF-Quick_Example' do
  pod 'KIF-Quick', :path => '../'

  target 'KIF-Quick_Tests' do
    inherit! :search_paths

    pod 'Quick', '0.9.3'    # Swift 2.3 compatible
    pod 'Nimble', '4.1.0'   # Swift 2.3 compatible
  end
end
